home:
    path: /
    controller: App\Controller\MainController::home

show:
    path: /post/{post}/show
    controller: App\Controller\MainController::show
    requirements:
            post: '\d*'

addreview:
    path: /addreview
    controller: App\Controller\MainController::addReview


subscribe:
    path: /subscribe
    controller: App\Controller\MainController::subscribe


addpost:
    path: /addpost
    controller: App\Controller\MainController::addPost


like:
    path: /post/{post}/show/like
    controller: App\Controller\MainController::addLike
    requirements:
            post: '\d*'

login:
    path: /login
    controller: App\Controller\MainController::login


logout:
    path: /logout
    controller: App\Controller\MainController::logout

addfakepost:
    path: /add/fake/post
    controller: App\Controller\FakerController::addRandomPost



    