home:
    path: /
    controller: App\Controller\MainController::home

show:
    path: /post/{post}/show
    controller: App\Controller\MainController::show
    requirements:
            post: '\d'

addreview:
    path: /addreview
    controller: App\Controller\MainController::addReview

author:
    path: /list/author
    controller: App\Controller\MainController::listAuthors


subscribe:
    path: /subscribe
    controller: App\Controller\MainController::subscribe


addauthor:
    path: /addauthor
    controller: App\Controller\MainController::addAuthor

addpost:
    path: /addpost
    controller: App\Controller\MainController::addPost

addpostform:    
    path: /addpostform
    controller: App\Controller\MainController::addPostForm
    methods: [POST]

addlike:
    path: /post/{post}/like
    controller: App\Controller\MainController::addLike
    requirements:
            post: '\d'